---
- name: Install nginx with Virtual Hosts
  hosts: webservers
  remote_user: runner
  become: true
  become_method: sudo
  gather_facts: no

  vars:
    sites:
    - 'iknt.ru'
    - 'fizmat.ru'
    - 'etis.com'

  roles:
  - nginx-vhosts
